import Head from "next/head";
import { useEffect, useState } from "react";
import Footer from "./footer";
import Navbar from "./navbar";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@900,700,500,301,701,300,501,401,901,400&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="flex flex-col min-h-screen mx-auto overflow-x-hidden">
        <div className="top-0 z-10 fixed w-full">
          <Navbar />
        </div>
        <main className="flex-grow">{children}</main>
        <div>
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Layout;
